sudo: false
language: php
dist: trusty
php:
  - 7.4
  - hhvm
install:
  - composer install
script:
  - vendor/phpunit/phpunit/phpunit --no-configuration tests/integration
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
