sudo: false
language: php
dist: trusty
php:
  - 7.4
  - hhvm
install:
  - composer install
script:
  - vendor/phpunit/phpunit/phpunit
# http://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
